apiVersion: v1
kind: Service
metadata:
  name: coredns-udp-svc-lb
  namespace: kube-system
  annotations:
    metallb.universe.tf/allow-shared-ip: coredns
spec:
  selector:
    k8s-app: kube-dns
  type: LoadBalancer
  ports:
    - protocol: UDP
      port: 53
---
apiVersion: v1
kind: Service
metadata:
  name: coredns-tcp-svc-lb
  namespace: kube-system
  annotations:
    metallb.universe.tf/allow-shared-ip: coredns
spec:
  selector:
    k8s-app: kube-dns
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 53
      name: tcp-first
    - protocol: TCP
      port: 9153
      name: tcp-second
