commonLabels:
  prometheus: default

tolerations:
  - key: node-role
    operator: Equal
    value: infra
    effect: NoSchedule

nodeSelector:
  cloud.google.com/gke-nodepool: infra-pool

alertmanager:
  ingress:
    enabled: true
    annotations: {
      kubernetes.io/ingress.class: nginx
    }
    path: /
    hosts:
      - alertmanager.35.188.170.169.xip.io

grafana:
  enabled: true

  defaultDashboardsEnabled: true

  adminPassword: superpassword

  additionalDataSources:
    - name: Loki
      type: Loki
      url: http://loki:3100

  ingress:
    enabled: true
    annotations: {
      kubernetes.io/ingress.class: nginx
    }
    path: /
    hosts:
      - grafana.35.188.170.169.xip.io

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
    serviceMonitorNamespaceSelector: {}

  ingress:
    enabled: true
    annotations: {
      kubernetes.io/ingress.class: nginx
    }
    path: /
    hosts:
      - prometheus.35.188.170.169.xip.io
